# Generated by Django 5.2.14 on 2026-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('img_link', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('search_query', models.CharField(max_length=100)),
                ('source', models.CharField(default='Jumia', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
