# Generated by Django 5.2.14 on 2026-05-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
