# Generated by Django 5.2.14 on 2026-05-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scraper', '0002_alter_product_link_alter_product_search_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='search_query',
        ),
        migrations.AddField(
            model_name='product',
            name='price_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='query',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
